#include "build/buildflag.h"

#define BUILDFLAG_INTERNAL_USE_NEW_TCMALLOC() 0

#define BUILDFLAG_INTERNAL_USE_ALLOCATOR_SHIM() 0

#define BUILDFLAG_INTERNAL_ENABLE_PROFILING() 0

//#define TCMALLOC_FOR_DEBUGALLOCATION